/**
 * List of project names that should be excluded from analysis
 * Add project names exactly as they appear in Asana
 */
export const projectSkipList: string[] = [
    "Altoona ~ Station Sites",
    "Johnstown ~ Station Sites",
    "State College ~ Station Sites",
    "Ticket Requests",
    "Client Updates",
    "Olean ~ Station Sites",
    "CapCity Kitchen",
    "DuBois/Clarion Websites",
    "Lewistown Station Websites",
    "NWPA ~ Station Sites",
    "Scrum Board",
    "Lebanon Station Websites",
    "Elmira Station Websites",
    "Mansfield Station Websites",
    "Frankfort Station Websites",
    "Selinsgrove (+Williamsport",
    "Bloomsburg) Station Websites",
    "Stroudsburg (+ Scranton/Wilkes-Barre) Station Websites",
    "API",
    "Live. Love. Local",
    "Radio Station TV Commercials",
    "DuBois Job Fair",
    "Radio Auction Website",
    "My Baby Bigfoot",
    "Burro E-Commerce Addition",
    "Dev Code Snippets",
    "Parkersburg Station Websites",
    "RadioNOVO APP",
    "7MM Streaming App",
    "7MM 7MC Event Collateral",
    "Davison Snacks T-Shirt Design",
    "Elmira GSM Video",
    "Siteground Website Transfers",
    "Bowling Green Station Websites",
    "7MM Susquehanna Employment Page",
    "Ticket Board",
    "Rockey Auctions (Redesign)",
    "7MM Sports",
    "92 Mix FM",
    "Research & Development",
    "7 Mountains Sports Replay Animation",
    "Project overview",
    "Mock project",
    "Spooky PA landing page",
    "7MM Web Project",
];
